### PR TITLE
fsl_lpi2c: Don't reset FIFOs on NAK

### PR DESCRIPTION
**Pull request by arturo182**
Patch courtesy of @mubes

### CODE REVIEW

**Comment by arturo182** [comment]
@tannewt not sure if you get notifications for this repo

**Comment by arturo182** [comment]
@ladyada can you merge?

**Comment by ladyada** [comment]
sure, i did not do a review

**Review by tannewt — COMMENTED** [review]
Looks good to me! Sorry I was out. Will add you, @arturo182, as a collaborator.

**Pull request merged**
